### ISSUE TITLE
Ignores Port config in /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by Safari77** [digitalocean/droplet-agent#33]
Console does not work, I get only `Connecting to droplet`.

tcpdump shows 162.243.188.66 attempts to connect my port 22, but I have sshd running in another port.
Starting the console should also display `Connecting to droplet ip:port` to ease debugging in the beginning (it does not come with a man page or README).

Parsing the sshd_config should not  be necessary, `droplet-agent` could support a config file where the port is specified.

**Comment by house-lee** [comment]
👋 Hi @Safari77 ,

Thanks for the suggestion. I'll definitely forward it to our PM and UX team.

For the first release we only supports sshd running on port 22, but YES, support for non-22 port is one of our planned works.  However there are many edge cases that we need to cover, also to guarantee customers' privacy & security, every plan we made has to go through a full review process to make sure we are doing everything we have our customers' consent for (including collecting what port the sshd is running on), therefore this feature may arrive a bit slower. 

Thanks again for reporting the issue and please stay tuned for our future updates. 

I'm closing this issue for now. Feel free to reopen it if you have something to add.
