### ISSUE TITLE
grub-install: error: cannot find efi directory

### ISSUE THREAD

**Issue by futurelinkug** [digitalocean/droplet-agent#66]
![Screenshot from 2023-01-23 17-06-51](https://user-images.githubusercontent.com/69959970/214069246-77255f48-90bb-42fb-85e4-991d1ad2de7a.png)
**Describe the bug**
When i try to install the droplet agent using 
`wget -qO- https://repos-droplet.digitalocean.com/install.sh | sudo bash`
`
I get this error: 
grub-install: error: cannot find efi directory`

the droplet is Ubuntu 16.04.6 (LTS) x64

**Comment by house-lee** [comment]
👋 Hi @futurelinkug , it seems you are experiencing issue with the do-agent not this droplet-agent (sorry I admit that the naming is indeed a bit confusing 😅 ), you may want to report an issue there: 
https://github.com/digitalocean/do-agent
